```{r}
news_cnt_df <- read.csv("../../outputs/data/08_01_02_entity_race_gender_expertise_news_count_daily_mail_only.csv")
```

```{r}

head(news_cnt_df)
names(news_cnt_df)

table(news_cnt_df$sex)
table(news_cnt_df$pronoun)
table(news_cnt_df$race)
table(news_cnt_df$urm)
table(news_cnt_df$pronoun_urm)
table(news_cnt_df$public_health_researcher)
table(news_cnt_df$practitioner)
table(news_cnt_df$non_public_health_researcher)
table(news_cnt_df$policymaker)
table(news_cnt_df$industry_expert)
table(news_cnt_df$celebrity)
table(news_cnt_df$journalist)
table(news_cnt_df$expertise_label_by_relative_expertise)
table(news_cnt_df$expertise_label_by_relative_reach)

news_cnt_df$news_count_gt_1 <- ifelse(news_cnt_df$news_count > 1,1,0)
news_cnt_df$news_count_gt_2 <- ifelse(news_cnt_df$news_count > 2,1,0)

news_cnt_df$urm_10 <- ifelse(news_cnt_df$urm == "Yes",1,0)
news_cnt_df$female_10 <- ifelse(news_cnt_df$sex == "Female",1,0)
news_cnt_df$main_prof_pm_10 <- ifelse(news_cnt_df$expertise_label_by_relative_expertise == "policymaker",1,0)
news_cnt_df$main_prof_ph_10 <- ifelse(news_cnt_df$expertise_label_by_relative_expertise == "public_health_researcher",1,0)
news_cnt_df$main_prof_celebrity_10 <- ifelse(news_cnt_df$expertise_label_by_relative_expertise == "celebrity",1,0)
news_cnt_df$main_prof_journalist_10 <- ifelse(news_cnt_df$expertise_label_by_relative_expertise == "journalist",1,0)
news_cnt_df$main_prof_ie_10 <- ifelse(news_cnt_df$expertise_label_by_relative_expertise == "industry_expert",1,0)
news_cnt_df$main_prof_practitioner_10 <- ifelse(news_cnt_df$expertise_label_by_relative_expertise == "practitioner",1,0)
news_cnt_df$main_prof_nph_10 <- ifelse(news_cnt_df$expertise_label_by_relative_expertise == "non_public_health_researcher",1,0)
news_cnt_df$main_prof_celebrity_journalist_ie_10 <- ifelse(news_cnt_df$main_prof_journalist_10 == 1 | news_cnt_df$main_prof_ie_10 == 1 | news_cnt_df$main_prof_celebrity_10 == 1,1,0)

news_cnt_df$reach_prof_pm_10 <- ifelse(news_cnt_df$expertise_label_by_relative_reach == "policymaker",1,0)
news_cnt_df$reach_prof_ph_10 <- ifelse(news_cnt_df$expertise_label_by_relative_reach == "public_health_researcher",1,0)
news_cnt_df$reach_prof_celebrity_10 <- ifelse(news_cnt_df$expertise_label_by_relative_reach == "celebrity",1,0)
news_cnt_df$reach_prof_journalist_10 <- ifelse(news_cnt_df$expertise_label_by_relative_reach == "journalist",1,0)
news_cnt_df$reach_prof_ie_10 <- ifelse(news_cnt_df$expertise_label_by_relative_reach == "industry_expert",1,0)
news_cnt_df$reach_prof_practitioner_10 <- ifelse(news_cnt_df$expertise_label_by_relative_reach == "practitioner",1,0)
news_cnt_df$reach_prof_nph_10 <- ifelse(news_cnt_df$expertise_label_by_relative_reach == "non_public_health_researcher",1,0)
news_cnt_df$reach_prof_celebrity_journalist_ie_10 <- ifelse(news_cnt_df$reach_prof_journalist_10 == 1 | news_cnt_df$reach_prof_ie_10 == 1 | news_cnt_df$reach_prof_celebrity_10 == 1,1,0)

news_cnt_df$non_urm_she <- ifelse(news_cnt_df$pronoun_urm == "non_urm_she",1,0)
news_cnt_df$non_urm_he <-  ifelse(news_cnt_df$pronoun_urm == "non_urm_he",1,0) # reference
news_cnt_df$urm_or_they <- ifelse(news_cnt_df$non_urm_she == 0 & news_cnt_df$non_urm_he == 0,1,0)
news_cnt_df$white <- ifelse(news_cnt_df$race == "White/European",1,0) # reference
news_cnt_df$non_white <- ifelse(news_cnt_df$white == 0,1,0)
news_cnt_df$non_public_health_researcher_10 <- ifelse(news_cnt_df$non_public_health_researcher == "Yes",1,0)
news_cnt_df$public_health_researcher_10 <- ifelse(news_cnt_df$public_health_researcher == "Yes",1,0)
news_cnt_df$practitioner_10 <- ifelse(news_cnt_df$practitioner == "Yes",1,0)
news_cnt_df$policymaker_10 <- ifelse(news_cnt_df$policymaker == "Yes",1,0)
news_cnt_df$industry_expert_10 <- ifelse(news_cnt_df$industry_expert == "Yes",1,0)
news_cnt_df$celebrity_10 <- ifelse(news_cnt_df$celebrity == "Yes",1,0)
news_cnt_df$journalist_10 <-ifelse(news_cnt_df$journalist == "Yes",1,0)
news_cnt_df$indexpert_celebrity_10 <- ifelse(news_cnt_df$industry_expert_10 == 1 | news_cnt_df$celebrity_10 == 1,1,0)
news_cnt_df$indexpert_celebrity_journalist_10 <- ifelse(news_cnt_df$indexpert_celebrity_10 == 1 | news_cnt_df$journalist_10 == 1, 1, 0)
# reference: non public health researcher
quantile(news_cnt_df$news_count,probs=seq(0,1,0.01))
# 61%: 1.00, 62%: 1.16, 63%: 2.00

news_cnt_df_nothey_available <- news_cnt_df[news_cnt_df$expertise_label_by_relative_expertise != 'not_available' & news_cnt_df$pronoun != "They",]
dim(news_cnt_df_nothey_available)

# Intersection of race/gender and profession

# non_urm_she & PH , non-urm-she & policy maker
news_cnt_df$non_urm_she_ph <- ifelse(news_cnt_df$non_urm_she == 1 & news_cnt_df$public_health_researcher_10 == 1,1,0)
news_cnt_df$non_urm_she_policymaker <- ifelse(news_cnt_df$non_urm_she == 1 & news_cnt_df$policymaker_10 == 1,1,0)

# urm_or_they & PH, urm_or_they & policy maker
news_cnt_df$urm_or_they_ph <- ifelse(news_cnt_df$urm_or_they == 1 & news_cnt_df$public_health_researcher_10 == 1,1,0)
news_cnt_df$urm_or_they_policymaker <- ifelse(news_cnt_df$urm_or_they == 1 & news_cnt_df$policymaker_10 == 1,1,0)

# Intersection of professions
# policy maker & PH researcher (1), PH researcher & practitioner (2)
news_cnt_df$policymaker_ph <- ifelse(news_cnt_df$policymaker_10 == 1 & news_cnt_df$public_health_researcher_10 == 1,1,0)
news_cnt_df$ph_practitioner <- ifelse(news_cnt_df$practitioner_10 == 1 & news_cnt_df$public_health_researcher_10 == 1,1,0)
```
```{r}
# policy maker but not PH researcher (3), PH researcher but not practitioner (4) -- complement of other binary indicators
# other professions: ind experts, journalists, celebrities -- let us not consider interactions for these occupations

### Part 1: outcome = # of mentions > 2 ###

## No collapse ##

# Model with (1) interactions between two professions and (2) interactions between race/gender and profession
# > 1
# industry expert, celebrity, and journalist kept separate
log_reg_gt1_interaction2 <- glm(news_count_gt_1 ~  non_urm_she + urm_or_they + 
                   policymaker_10 +  
                   public_health_researcher_10 +
                   practitioner_10 + 
                   #non_public_health_researcher_10 +
                   industry_expert_10 + 
                   celebrity_10 + 
                   journalist_10 +
                   # professional interactions
                   policymaker_ph + ph_practitioner + public_health_researcher:practitioner +
                   # race/gender and profession
                   non_urm_she_ph + 
                   non_urm_she_policymaker + 
                   urm_or_they_ph + 
                   urm_or_they_policymaker, data = news_cnt_df, family = "binomial")
summary(log_reg_gt1_interaction2)
confint.default(log_reg_gt1_interaction2)

#mod1b <- lrm(y ~ x) need to investigate this further

cor(log_reg_gt1_interaction2$fitted.values, news_cnt_df$news_count_gt_1)
```
```{r}
# Simple - No interaction
log_reg_gt1_simple_nointeraction <- glm(news_count_gt_1 ~ urm_10 + female_10 +
                                          main_prof_pm_10 +
                                        main_prof_ph_10 +
                                        main_prof_celebrity_10 +
                                        main_prof_journalist_10 +
                                        main_prof_ie_10 +
                                        main_prof_practitioner_10,
                                        data=news_cnt_df_nothey_available, family="binomial")
summary(log_reg_gt1_simple_nointeraction)
exp(coef(log_reg_gt1_simple_nointeraction))
confint.default(log_reg_gt1_simple_nointeraction)
exp(cbind(OR = coef(log_reg_gt1_simple_nointeraction), confint(log_reg_gt1_simple_nointeraction)))
cor(log_reg_gt1_simple_nointeraction$fitted.values, news_cnt_df_nothey_available$news_count_gt_1)
cor(log_reg_gt1_simple_nointeraction$fitted.values, news_cnt_df_nothey_available$news_count_gt_1,method='spearman')
cor(log_reg_gt1_simple_nointeraction$fitted.values, news_cnt_df_nothey_available$news_count_gt_1,method='kendall')
```
